version: "3.9"

services:
  db:
    image: postgres:15
    container_name: l0-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - l0

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER}
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLUSTER_ID=${KAFKA_CLUSTER_ID}
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - l0

  kafka-init:
    image: bitnami/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        echo 'Ждём Kafka и создаём топик orders...'
        /opt/bitnami/kafka/bin/kafka-topics.sh \
          --create \
          --if-not-exists \
          --bootstrap-server ${KAFKA_BROKER} \
          --replication-factor 1 \
          --partitions 1 \
          --topic orders
        echo 'Топик orders готов'
    networks:
      - l0

  order-service:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.srvc
    environment:
      DATABASE_URL: ${ORDER_DATABASE_URL}
      KAFKA_URL: ${ORDER_KAFKA_URL}
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - "${ORDER_APP_PORT}:8080"
    networks:
      - l0

  producer:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.prdc
    environment:
      DATABASE_URL: ${PRODUCER_DATABASE_URL}
      KAFKA_URL: ${PRODUCER_KAFKA_URL}
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - l0
  migrator:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "-path", "/migrations",
        "-database", "${POSTGRES_URL}",
        "up"
      ]
    volumes:
      - ../migrations:/migrations
    networks:
      - l0
  migrator-down:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "-path", "/migrations",
        "-database", "${POSTGRES_URL}",
        "down", "${DOWN_STEPS:-1}"
      ]
    volumes:
      - ../migrations:/migrations
    networks:
      - l0
networks:
  l0:
    driver: bridge
