version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS=orders:3:1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLUSTER_ID=abvgd
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092 | grep -q '^orders$'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - l0

  order-service:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.srvc
    environment:
      DATABASE_URL: "postgres://postgres:12345@host.docker.internal:5432/l0?sslmode=disable"
      KAFKA_URL: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - l0

  producer:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.prdc
    environment:
      DATABASE_URL: "postgres://myuser:mypass@host.docker.internal:5432/mydb?sslmode=disable"
      KAFKA_URL: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - l0

networks:
  l0:
    driver: bridge
